[build]
    command = "npm run build:app" # the command you run to build this file
    functions = "dist/functions" # netlify-lambda builds to this folder AND Netlify reads functions from here
    publish = "dist" # create-react-app builds to this folder, Netlify should serve all these files statically